import {describe,it,expect,vi} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {createApi,authorized,tokenHash,type Core,type Env,type Article} from '../src/adapter';
import {createSite,createRustCore} from '../src/runtime';
const now=Date.parse('2026-10-01T05:00:00Z');
const article:Article={id:'one',title:'New model',url:'https://openai.com/news/model',source:'openai',category:'模型进展',summary:'Original excerpt',published_at:new Date(now).toISOString(),fetched_at:new Date(now).toISOString()};
const source={id:'openai',name:'OpenAI',home:'https://openai.com/news/'};
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync('../drizzle/0000_dear_carlie_cooper.sql','utf8'));function prepare(sql:string){let values:unknown[]=[];return {bind(...v:unknown[]){values=v;return this},async run(){const r=db.prepare(sql).run(...values as any[]);return {meta:{changes:Number(r.changes)}}},async all(){return {results:db.prepare(sql).all(...values as any[])}},async first(){return db.prepare(sql).get(...values as any[])??null}};}return {db,DB:{prepare} as unknown as D1Database};}
async function setup(options:{sources?:typeof source[];parse?:Core['parse'];fetchFeed?:any}={}){const d=database();const env:Env={DB:d.DB,REFRESH_TOKEN_SHA256:await tokenHash('test-token')};let time=now;let seq=0;const core:Core={sources:options.sources??[source],parse:options.parse??(()=>[article])};const fetchFeed=options.fetchFeed??vi.fn(async()=>new Response('<rss/>'));const api=createApi(core,{now:()=>time,uuid:()=>`run-${++seq}`,fetchFeed});return {api,env,db:d.db,core,fetchFeed,advance:()=>{time+=3600000;},async refresh(headers:Record<string,string>={Authorization:'Bearer test-token'}){return api(new Request('https://site.test/api/refresh',{method:'POST',headers}),env)},async news(query=''){return (await api(new Request('https://site.test/api/news'+query),env)).json()}};}
describe('authorization',()=>{
 it('fails closed for missing invalid and wrong credentials',async()=>{for(const hash of [undefined,'abc','F'.repeat(64)])expect(await authorized(new Request('https://site.test'),hash)).toBe(false);const hash=await tokenHash('good');for(const auth of ['', 'Basic good','Bearer wrong','Bearer '+'a'.repeat(4096)])expect(await authorized(new Request('https://site.test',{headers:{Authorization:auth}}),hash)).toBe(false);expect(await authorized(new Request('https://site.test',{headers:{Authorization:'Bearer good'}}),hash)).toBe(true);});
});
describe('HTTP and database',()=>{
 it('public reads return persisted records true counts and bounded pagination',async()=>{const s=await setup();const empty:any=await s.news();expect(empty.articles).toEqual([]);expect(empty.run).toBeNull();expect(empty.schedule).toBe('尚未启用');expect(empty.stats.total_articles).toBe(0);expect((await s.refresh()).status).toBe(200);const news:any=await s.news('?limit=1&offset=0');expect(news.articles[0].id).toBe('one');expect(news.stats).toEqual({total_articles:1,recent_articles:1,total_sources:1});expect(news.pagination).toEqual({total:1,offset:0,limit:1,has_more:false});expect(news.run.status).toBe('success');expect((await s.news('?limit=0&offset=999999999') as any).pagination).toEqual({total:1,offset:1000000,limit:1,has_more:false});expect((await s.news('?limit=-1&offset=x') as any).pagination.limit).toBe(50);expect((await s.news('?limit=999') as any).pagination.limit).toBe(350);s.db.exec("INSERT INTO settings VALUES('schedule','hourly')");expect((await s.news() as any).schedule).toBe('hourly');});
 it('excludes future records from the rolling day count',async()=>{const future={...article,published_at:new Date(now+3600000).toISOString()};const s=await setup({parse:()=>[future]});await s.refresh();expect((await s.news() as any).stats.recent_articles).toBe(0);});
 it('rejects unsafe requests and reports health/missing routes',async()=>{const s=await setup();expect((await s.refresh({})).status).toBe(401);expect((await s.refresh({Authorization:'Bearer test-token',Origin:'https://other.test'})).status).toBe(403);expect((await s.api(new Request('https://site.test/api/refresh'),s.env)).status).toBe(405);expect((await s.api(new Request('https://site.test/api/news',{method:'POST'}),s.env)).status).toBe(405);expect((await s.api(new Request('https://site.test/api/unknown'),s.env)).status).toBe(404);expect(await (await s.api(new Request('https://site.test/healthz'),s.env)).json()).toEqual({status:'ok',runtime:'rust-wasm'});});
 it('throttles repeat success and upserts without counting updates as inserts',async()=>{const s=await setup();expect(await (await s.refresh()).json()).toMatchObject({inserted:1,processed:1,status:'success'});expect(await (await s.refresh()).json()).toMatchObject({status:'not_due'});s.advance();expect(await (await s.refresh({Authorization:'Bearer test-token',Origin:'https://site.test'})).json()).toMatchObject({inserted:0,processed:1});expect((await s.news() as any).articles).toHaveLength(1);expect((await s.news() as any).run.added).toBe(0);});
 it('prevents overlapping refresh without releasing another lease',async()=>{const s=await setup();s.db.prepare("INSERT INTO settings VALUES('ingest_lease',?)").run(`${now+9999}:other`);expect(await (await s.refresh()).json()).toMatchObject({status:'busy'});expect(s.db.prepare("SELECT value FROM settings").get()?.value).toBe(`${now+9999}:other`);});
 it('retains old records on all-source failure and reports partial successes',async()=>{let fail=false;const s=await setup({fetchFeed:vi.fn(async()=>new Response('feed',{status:fail?503:200}))});await s.refresh();fail=true;s.advance();expect(await (await s.refresh()).json()).toMatchObject({status:'failed',inserted:0});expect((await s.news() as any).articles).toHaveLength(1);const partial=await setup({sources:[source,{id:'google',name:'Google',home:'https://blog.google/'}],fetchFeed:vi.fn(async(url:string)=>{if(url.includes('blog.google'))throw Error('Unavailable');return new Response('ok');})});expect(await (await partial.refresh()).json()).toMatchObject({status:'partial',inserted:1});});
 it.each(['empty','oversize','parse','unknown','nonerror'])('records %s feed failures',async(kind)=>{const s=await setup({sources:kind==='unknown'?[{...source,id:'missing'}]:undefined,parse:kind==='parse'?()=>{throw Error('Malformed RSS')}:undefined,fetchFeed:vi.fn(async()=>{if(kind==='nonerror')throw 'failure';if(kind==='empty')return new Response(null);return new Response(kind==='oversize'?'x'.repeat(3000001):'ok');})});const result:any=await (await s.refresh()).json();expect(result.status).toBe('failed');expect(result.details[0].error).toBeTruthy();expect(s.db.prepare("SELECT value FROM settings WHERE key='ingest_lease'").get()?.value).toBe('0');});
 it('reports storage unavailable without leaking internals',async()=>{const s=await setup();s.db.close();const r=await s.api(new Request('https://site.test/api/news'),s.env);expect(r.status).toBe(503);expect(await r.json()).toEqual({error:'Service temporarily unavailable'});});
 it('uses defaults with an empty source list',async()=>{const s=await setup();const api=createApi({sources:[],parse:()=>[]});const r=await api(new Request('https://site.test/api/refresh',{method:'POST',headers:{Authorization:'Bearer test-token'}}),s.env);expect(r.status).toBe(200);});
});
describe('Rust and static runtime adapter',()=>{
 it('calls Rust bindings and rejects malformed envelopes',()=>{const bindings={public_sources_json:()=>JSON.stringify([source]),normalize_feed_json:()=>JSON.stringify({ok:true,articles:[article]})};const core=createRustCore(bindings);expect(core.sources).toEqual([source]);expect(core.parse('openai','xml','time')).toEqual([article]);for(const envelope of [{ok:false,error:'Bad feed'},{ok:true},{ok:false}])expect(()=>createRustCore({...bindings,normalize_feed_json:()=>JSON.stringify(envelope)}).parse('x','x','x')).toThrow();});
 it('serves static assets SPA fallback headers and API',async()=>{const s=await setup();const site=createSite(s.core,{'/index.html':{body:'<html>AI</html>',type:'text/html'},'/assets/app.js':{body:'code',type:'application/javascript'}});const get=(p:string,method='GET')=>site.fetch(new Request('https://site.test'+p,{method}),s.env);expect(await (await get('/')).text()).toBe('<html>AI</html>');expect(await (await get('/sources')).text()).toContain('AI');expect(await (await get('/','HEAD')).text()).toBe('');expect((await get('/','POST')).status).toBe(405);expect((await get('/missing.js')).status).toBe(404);expect((await get('/assets/app.js')).headers.get('Cache-Control')).toContain('immutable');expect((await get('/')).headers.get('Content-Security-Policy')).toContain("object-src 'none'");expect((await get('/api/news')).status).toBe(200);expect((await get('/healthz')).status).toBe(200);});
});
